# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.1'

services:

  nginx:
    container_name: nginxalbumviewer
    image: nginxalbumviewer
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    # volumes:.
    #   - ./dist:/usr/share/nginx/html
    ports:
      - "8081:80"
#      - "443:443"
    networks:
      - app-network

  aspnet:
    container_name: 'westwindalbumviewer'
    image: 'rickstrahl/albumviewer:albumviewer'
    build:
      context: ./src/AlbumViewerNetCore
      dockerfile: Dockerfile
 #   volumes:
 #     - ./src/AlbumViewerNetCore:/var/www/albumviewer
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge